export const portfolioData = [
  {
    id: 1,
    link: "https://www.radarpictures.com/",
    image: "/radar_pictures.jpg",
    alt: "Radar Pictures",
    text: "Radar Pictures",
  },
  {
    id: 2,
    link: "https://www.bevmart.com/",
    image: "/bevmart.jpg",
    alt: "Bevmart",
    text: "Bevmart",
  },
  {
    id: 3,
    link: "https://www.themyx.com/",
    image: "/myx.jpg",
    alt: "The Myx",
    text: "The MYX",
  },
  {
    id: 4,
    link: "https://parkburlingtonmap.app/",
    image: "/park_burlington.jpg",
    alt: "Park Burlington",
    text: "Park Burlington",
  },
  {
    id: 5,
    link: "https://hidden-fortress-73610.herokuapp.com/",
    image: "/mock_blog.jpg",
    alt: "mock blog project link",
    text: "Mock Blog",
  },
  {
    id: 6,
    link: "https://secure-fjord-65417.herokuapp.com/",
    image: "/yelpington.jpg",
    alt: "yelpington project link",
    text: "Yelpington",
  },
  {
    id: 7,
    link: "https://stark-plateau-02827.herokuapp.com/",
    image: "/trip_tac_toe.jpg",
    alt: "trip-tac-toe game link",
    text: "Trip-Tac-Toe",
  },
  {
    id: 8,
    link: "https://github.com/JonChamplain?tab:repositories",
    image: "/github.jpg",
    alt: "github link",
    text: "Github",
  },
]
